config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'landing#index'

  namespace :manager do
    resources :accounts
    root 'accounts#index'
  end

  namespace :regular do
    root 'landing#index'
    resources :transfers, only:[:new, :create]
    resources :deposits, only:[:new, :create]
    resources :withdraws, only:[:new, :create]
    resources :statements, only:[:index]
    resources :investments, except:[:delete, :show]
  end

  namespace :vip do
    root 'landing#index'
    resources :transfers, only:[:new, :create]
    resources :deposits, only:[:new, :create]
    resources :withdraws, only:[:new, :create]
    resources :statements, only:[:index]
    resources :investments, except:[:delete, :show]
    resources :visits, only:[:index]
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                 :integer          not null, primary key
#  name               :string(255)      default(""), not null
#  role               :integer          not null
#  acc_number         :string(255)      default(""), not null
#  encrypted_password :string(255)      default(""), not null
#  sign_in_count      :integer          default(0), not null
#  current_sign_in_at :datetime
#  last_sign_in_at    :datetime
#  current_sign_in_ip :string(255)
#  last_sign_in_ip    :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # :recoverable, :rememberable
  has_many :financial_operations
  has_many :stocks
  has_many :visit_calls

  devise :database_authenticatable, :registerable, :trackable, :validatable
  enum role: [:regular, :vip, :manager]

  scope :presentable, -> {where.not(role: roles[:manager])}

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def self.roles_collection
    possible_roles = roles.dup
    possible_roles.delete("manager")
    possible_roles.keys
  end

  def build_operation(t_id, op=last_operation)
    new_operation = financial_operations.build(financial_transaction_id:t_id)
    new_operation.transfer_values(op)
  end

  def last_operation
    financial_operations.last || financial_operations.build
  end

  def transfer_limit
    return 1000.to_d if regular?
    BigDecimal::INFINITY
  end
end

app/controllers/manager/accounts_controller.rb
module Manager
  class AccountsController < Manager::ApplicationController
    before_action :set_account, only:[ :show]
    def index
      @accounts= Account.presentable
    end

    def new
      @account = AccountForm.new(Account.new)
    end

    def create
      @account= AccountForm.new(Account.new)
      if @account.validate(account_params)
        #TODO fix this code, this is a workaround
        Account.create!(name: @account.name,
                        acc_number: @account.acc_number,
                        role: @account.role,
                        password:@account.password,
                        password_confirmation: @account.password_confirmation)
        redirect_to manager_accounts_path
      else
        render :new
      end
    end

    def edit
      @account= AccountForm.new(Account.find(params[:id]))
    end

    def update
      acc = Account.find(params[:id])
      @account= AccountForm.new(acc)
      if @account.validate(account_params)
        #TODO fix this code, this is a workaround
        acc.name = @account.name
        acc.role = @account.role
        acc.password = @account.password if @account.password.present?
        acc.password_confirmation = @account.password_confirmation if @account.password.present?
        acc.save!
        redirect_to manager_accounts_path, notice:"Conta alterada com sucesso"
      else
        render :edit
      end
    end

    def show
      @acc = @account.decorate
    end

    private
    def set_account
      @account= Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :acc_number, :password, :password_confirmation, :role)
    end
  end
end

app/controllers/manager/application_controller.rb
module Manager
  class ApplicationController < ActionController::Base

    rescue_from Exception, :with => :general_error
    protect_from_forgery with: :exception

    layout 'manager'
    before_action :authenticate_account!
    before_action :authenticate_manager!

    private
    def authenticate_manager!
      return redirect_to current_account.decorate.root_path unless current_account.manager?
    end

    def general_error(exception)
      Rails.logger.error(exception.message)
      Rails.logger.error(exception.backtrace.join("\n"))
      return redirect_to current_account.decorate.root_path, alert: "Infelizmente não foi possível realizar a transação.\nPor favor tente novamente em alguns minutos."
    end
  end
end

app/views/manager/accounts/_form.slim
= simple_form_for([:manager,@account]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :acc_number, disabled: @account.persisted?, hint: 'You cannot change an account number.'
    = f.input :role, collection: Account.roles_collection, include_blank: false
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/manager/accounts/edit.slim
.card
  .title
    h3.center= "Conta #{@account.acc_number}"
  .content
    == render 'form'

app/views/manager/accounts/index.slim
.card
  .title
    h3.center Gerenciamento de Contas
  .content
    table
      thead
        tr
          th Conta
          th Nome
          th Tipo
          th
      tbody
        -@accounts.each do |acc|
          tr
            td= acc.acc_number
            td= acc.name
            td= acc.role
            td
              = link_to manager_account_path(acc), title: 'Ver Saldo' do
                i.fi-eye
              = link_to edit_manager_account_path(acc), title: 'Editar' do
                i.fi-pencil

app/views/manager/accounts/new.slim
.card
  .title
    h3.center Nova conta
  .content
    == render 'form'

app/views/manager/accounts/show.slim
.card
  .title
    h3.center= "Conta #{@acc.acc_number}"
  .content
    h4= "Saldo: #{@acc.formatted_balance}"
    hr
    ul
      -@acc.formatted_visit_calls.each do |v|
        li= v