config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'landing#index'

  namespace :manager do
    resources :accounts
    root 'accounts#index'
  end

  namespace :regular do
    root 'landing#index'
    resources :transfers, only:[:new, :create]
    resources :deposits, only:[:new, :create]
    resources :withdraws, only:[:new, :create]
    resources :statements, only:[:index]
    resources :investments, except:[:delete, :show]
  end

  namespace :vip do
    root 'landing#index'
    resources :transfers, only:[:new, :create]
    resources :deposits, only:[:new, :create]
    resources :withdraws, only:[:new, :create]
    resources :statements, only:[:index]
    resources :investments, except:[:delete, :show]
    resources :visits, only:[:index]
  end
end

app/controllers/regular/investments_controller.rb
class Regular::InvestmentsController < Regular::ApplicationController
  rescue_from InsuficientStocksException, :with => :not_enough_stocks
  # I know, I should use a proper route name
  # buy Stocks
  def index
    @acc=current_account.decorate
    @my_stocks = StockDecorator.decorate_collection(@acc.stocks)
    @available_stocks = Portfolio::STOCK_SYMBOLS.map{|symbol| Stock.new(stock_symbol: symbol).decorate}
  end

  def new
    @acc=current_account.decorate
    @investment = InvestmentForm.new(FinancialOperation.new)
    @investment.stock_symbol = params[:stock]
    return redirect_to vip_investments_path, alert: "Ação não disponível!" unless Portfolio::STOCK_SYMBOLS.include?(@investment.stock_symbol)
  end

  # I know, I should use a proper route name
  # buy Stocks
  def create
    @investment = InvestmentForm.new(FinancialOperation.new)
    if @investment.validate(params[:investment])
      Investment.new(current_account).buy(@investment.qtd.to_i, @investment.stock_symbol)
      ##
      return redirect_to vip_investments_path, notice:"Compra de ações efetuada com sucesso."
    else
      @acc=current_account.decorate
      render :new
    end
  end

  # I know, I should use a proper route name
  # Sell Stocks
  def edit
    @acc=current_account.decorate
    @investment = InvestmentForm.new(FinancialOperation.new)
    @stock = Stock.find(params[:id])
    @investment.stock_symbol= @stock.stock_symbol
  end

  # I know, I should use a proper route name
  # Sell Stocks
  def update
    @investment = InvestmentForm.new(FinancialOperation.new)
    if @investment.validate(params[:investment])
      @stock = Stock.find(params[:id])
      Investment.new(current_account).sell(@investment.qtd.to_i, @stock.stock_symbol)
      ##
      return redirect_to vip_investments_path, notice:"Venda de ações efetuada com sucesso."
    else
      @acc=current_account.decorate
      @investment.stock_symbol= @stock.stock_symbol
      render :new
    end
  end

  private
  def not_enough_stocks
    @acc= current_account.decorate
    return redirect_to vip_investments_path, alert: "Você não possui ações suficientes para essa operação."
  end
end

app/controllers/vip/application_controller.rb
module Vip
  class ApplicationController < ActionController::Base
    rescue_from Exception, :with => :general_error

    protect_from_forgery with: :exception

    layout 'vip'
    before_action :authenticate_account!
    before_action :authenticate_vip!

    private
    def authenticate_vip!
      return redirect_to current_account.decorate.root_path unless current_account.vip?
    end

    def general_error(exception)
      Rails.logger.error(exception.message)
      Rails.logger.error(exception.backtrace.join("\n"))
      return redirect_to current_account.decorate.root_path, alert: "Infelizmente não foi possível realizar a transação.\nPor favor tente novamente em alguns minutos."
    end
  end
end

app/controllers/vip/deposits_controller.rb
class Vip::DepositsController < Vip::ApplicationController
  def new
    @acc= current_account.decorate
    @deposit = DepositForm.new(FinancialOperation.new)
  end

  def create
    @deposit = DepositForm.new(FinancialOperation.new)
    if @deposit.validate(params[:deposit])
      Deposit.new(current_account).call(@deposit.ammount.to_d)
      ##
      return redirect_to current_account.decorate.root_path, notice: "Deposito efetuado com sucesso!"
    else
      @acc=current_account.decorate
      render :new
    end
  end
end

app/controllers/vip/investments_controller.rb
class Vip::InvestmentsController < Vip::ApplicationController
  rescue_from InsuficientStocksException, :with => :not_enough_stocks
  # I know, I should use a proper route name
  # buy Stocks
  def index
    @acc=current_account.decorate
    @my_stocks = StockDecorator.decorate_collection(@acc.stocks)
    @available_stocks = Portfolio::STOCK_SYMBOLS.map{|symbol| Stock.new(stock_symbol: symbol).decorate}
  end

  def new
    @acc=current_account.decorate
    @investment = InvestmentForm.new(FinancialOperation.new)
    @investment.stock_symbol = params[:stock]
    return redirect_to vip_investments_path, alert: "Ação não disponível!" unless Portfolio::STOCK_SYMBOLS.include?(@investment.stock_symbol)
  end

  # I know, I should use a proper route name
  # buy Stocks
  def create
    @investment = InvestmentForm.new(FinancialOperation.new)
    if @investment.validate(params[:investment])
      Investment.new(current_account).buy(@investment.qtd.to_i, @investment.stock_symbol)
      ##
      return redirect_to vip_investments_path, notice:"Compra de ações efetuada com sucesso."
    else
      @acc=current_account.decorate
      render :new
    end
  end

  # I know, I should use a proper route name
  # Sell Stocks
  def edit
    @acc=current_account.decorate
    @investment = InvestmentForm.new(FinancialOperation.new)
    @stock = Stock.find(params[:id])
    @investment.stock_symbol= @stock.stock_symbol
  end

  # I know, I should use a proper route name
  # Sell Stocks
  def update
    @investment = InvestmentForm.new(FinancialOperation.new)
    if @investment.validate(params[:investment])
      @stock = Stock.find(params[:id])
      Investment.new(current_account).sell(@investment.qtd.to_i, @stock.stock_symbol)
      ##
      return redirect_to vip_investments_path, notice:"Venda de ações efetuada com sucesso."
    else
      @acc=current_account.decorate
      @investment.stock_symbol= @stock.stock_symbol
      render :new
    end
  end

  private
  def not_enough_stocks
    @acc= current_account.decorate
    return redirect_to vip_investments_path, alert: "Você não possui ações suficientes para essa operação."
  end
end

app/controllers/vip/landing_controller.rb
class Vip::LandingController < Vip::ApplicationController
  def index
    @acc=current_account.decorate
  end
end

app/controllers/vip/statements_controller.rb
class Vip::StatementsController < Vip::ApplicationController
  def index
    @acc=current_account.decorate
    @operations = FinancialOperationDecorator.decorate_collection(current_account.financial_operations.last(20))
  end
end

app/controllers/vip/transfers_controller.rb
class Vip::TransfersController < Vip::ApplicationController
  def new
    @acc=current_account.decorate
    @transfer = TransferForm.new(FinancialOperation.new)
  end

  def create
    @transfer = TransferForm.new(FinancialOperation.new(account:current_account))
    if @transfer.validate(params[:transfer])
      Transfer.new(current_account).call(@transfer.ammount.to_d, @transfer.destination_account)
      ##
      return redirect_to current_account.decorate.root_path, notice: "Transferência realizada com sucesso!"
    else
      @acc=current_account.decorate
      render :new
    end
  end
end

app/controllers/vip/visits_controller.rb
class Vip::VisitsController < Vip::ApplicationController
  def index
    Visit.new(current_account).call
    redirect_to current_account.decorate.root_path, notice: "Visita solicitada"
  end
end

app/controllers/vip/withdraws_controller.rb
class Vip::WithdrawsController < Vip::ApplicationController
  def new
    @acc=current_account.decorate
    @withdraw = WithdrawForm.new(FinancialOperation.new)
  end

  def create
    @withdraw = WithdrawForm.new(FinancialOperation.new)
    if @withdraw.validate(params[:withdraw])
      Withdraw.new(current_account).call(@withdraw.ammount.to_d)
      ##
      return redirect_to current_account.decorate.root_path, notice: "Saque efetuado com sucesso!"
    else
      @acc=current_account.decorate
      render :new
    end
  end
end

app/helpers/regular/investment_helper.rb
module Regular::InvestmentHelper
end

app/helpers/vip/deposits_helper.rb
module Vip::DepositsHelper
end

app/helpers/vip/investment_helper.rb
module Vip::InvestmentHelper
end

app/helpers/vip/landing_helper.rb
module Vip::LandingHelper
end

app/helpers/vip/statements_helper.rb
module Vip::StatementsHelper
end

app/helpers/vip/transfers_helper.rb
module Vip::TransfersHelper
end

app/helpers/vip/withdraws_helper.rb
module Vip::WithdrawsHelper
end

app/views/vip/investments/edit.html.slim
.card
  .title
    h3.center= "Conta #{@acc.acc_number} - Investimentos"
  .content
    = simple_form_for([:vip, @investment], url: vip_investment_path(@stock.id), method: :patch ) do |f|
      = f.error_notification

      .form-inputs
        = f.input :stock_symbol, disabled: true
      .form-inputs
        = f.input :qtd
      = f.input :price, :as => "hidden", :input_html => {:value => Portfolio.cached_price(@investment.stock_symbol)}
      = f.input :stock_symbol, :as => "hidden"

      .form-actions
        a#submitBtn.button data-toggle="confirmationModal" Vender Ações

#confirmationModal.reveal data-close-on-click="true" data-reveal=""
  h3 Confirmação de compra!
  table
    tr
      th Ação
      td#c_stock_symbol
    tr
      th Quantidade
      td#c_qtd
    tr
      th= '*Total'
      td#c_total
    tr
      th Taxas
      td#c_tax
    tr
      th= '*Comissão'
      td#c_commision
    tr
      th= '*A receber'
      td#c_final

  h5= "*Valores sujeitos à variação da cotação"
  button.close-button aria-label=("Close reveal") data-close="" type="button"
    span aria-hidden="true" &times;
  button.button#submit Confirmar Venda

javascript:
  $('#submitBtn').click(function () {
      $('#c_stock_symbol').text($('#investment_stock_symbol').val());
      $('#c_qtd').text($('#investment_qtd').val());
      var total = Number($('#investment_price').val()) * Number($('#investment_qtd').val());
      $('#c_total').text(round_2f(total));
      $('#c_tax').text(round_2f(#{Investment::FEE}));
      var commission = round_2f(#{Investment::COMMISSION_RATE}*total);
      $('#c_commision').text(round_2f(commission));
      $('#c_final').text(total - commission - #{Investment::FEE});
  });

  $('#submit').click(function () {
      $('#new_investment').submit();
  });

app/views/vip/investments/index.slim
.card
  .title
    h3.center= "Conta #{@acc.acc_number} - Investimento - Ações Disponíveis"
  .content
    table
      thead
        tr
          th Ação
          th Preço
          th
      tbody
        -@available_stocks.each do |st|
          tr
            td= st.stock_symbol
            td= st.formatted_current_price
            td= link_to("Comprar", new_vip_investment_path(stock: st.stock_symbol))
.card
  .title
    h3.center= "Conta #{@acc.acc_number} - Investimento - Portfólio"
  .content
    table
      thead
        tr
          th Ação
          th Quantidade
          th Preço de Compra
          th Preço Atual
          Th Rendimento
          th
      tbody
        -@my_stocks.each do |st|
          tr
            td= st.stock_symbol
            td= st.qtd
            td= st.formatted_price
            td= st.formatted_current_value
            td= st.income_percentage
            td= link_to("Vender", edit_vip_investment_path(st))

app/views/vip/investments/new.html.slim
.card
  .title
    h3.center= "Conta #{@acc.acc_number} - Investimentos"
  .content
    = simple_form_for([:vip, @investment]) do |f|
      = f.error_notification

      .form-inputs
        = f.input :stock_symbol, disabled: true
      .form-inputs
        = f.input :qtd
      = f.input :price, :as => "hidden", :input_html => { :value => Portfolio.cached_price(@investment.stock_symbol) }
      = f.input :stock_symbol, :as => "hidden"

      .form-actions
        a#submitBtn.button data-toggle="confirmationModal" Comprar Ações

#confirmationModal.reveal data-close-on-click="true" data-reveal=""
  h3 Confirmação de compra!
  table
    tr
      th Ação
      td#c_stock_symbol
    tr
      th Quantidade
      td#c_qtd
    tr
      th= '*Total'
      td#c_total
  h5= "*Valor sujeito à variação da cotação"
  button.close-button aria-label=("Close reveal") data-close="" type="button"
    span aria-hidden="true" &times;
  button.button#submit Confirmar Compra

javascript:
    $('#submitBtn').click(function () {
        $('#c_stock_symbol').text($('#investment_stock_symbol').val());
        $('#c_qtd').text($('#investment_qtd').val());
        var total = Number($('#investment_price').val()) * Number($('#investment_qtd').val());
        $('#c_total').text(round_2f(total));
    });

    $('#submit').click(function () {
        $('#new_investment').submit();
    });